import multiprocessing as mp
import os
import sys
import time
import importlib
import traceback

import numpy as np

__all__ = ['Potential', 'Potential_NoMP', 'NN_Potential', 'Potential_Direct']


_RESERVED_POT_STOP = ("PYVIBDMC_RESERVED_POT_STOP",)
_RESERVED_POT_CALL = "PYVIBDMC_RESERVED_POT_CALL"
_RESERVED_TASK_QUEUE = None
_RESERVED_RESULT_QUEUE = None


def _init_reserved_potential_queues(task_queue, result_queue):
    global _RESERVED_TASK_QUEUE, _RESERVED_RESULT_QUEUE
    _RESERVED_TASK_QUEUE = task_queue
    _RESERVED_RESULT_QUEUE = result_queue


def _reserved_potential_worker(pot_func):
    """Long-lived potential worker used to pin single-core potential calls to one process."""
    while True:
        task = _RESERVED_TASK_QUEUE.get()
        if task == _RESERVED_POT_STOP:
            return

        tag, task_id, cds, pot_kwargs = task
        if tag != _RESERVED_POT_CALL:
            _RESERVED_RESULT_QUEUE.put((task_id, False, None, f"Unknown reserved potential task tag: {tag!r}"))
            continue

        try:
            if pot_kwargs is None:
                result = pot_func(cds)
            else:
                result = pot_func(cds, pot_kwargs)
            _RESERVED_RESULT_QUEUE.put((task_id, True, result, None))
        except BaseException:
            _RESERVED_RESULT_QUEUE.put((task_id, False, None, traceback.format_exc()))


class Potential:
    """
    A potential handler that is able to call python functions that
    call .so files, either generated by f2py or loaded in by ctypes.
    :param potential_function: The name of a python function (user specified) that will take in a n x m x 3 stack of geometries and return a 1D numpy array filled with potential values in hartrees.
    :type potential_function: str
    :param potential_dir: The *absolute path* to the directory that contains the .so file and .py file. If it"s a python function, then just the absolute path to your .py file.
    :type: str
    :param num_cores: Number of chunks used for potential energy calls. This also sets the initial multiprocessing pool size. The pool may later be enlarged when sharing it with importance sampling.
    :type: int
    """

    def __init__(self,
                 potential_function,
                 potential_directory,
                 python_file,
                 num_cores=1,
                 pass_timestep=False,
                 pot_kwargs=None,
                 ):
        self.potential_function = potential_function
        self.python_file = python_file
        self.potential_directory = potential_directory
        self.num_cores = num_cores
        self.pool_num_cores = num_cores
        self._reserved_task_queue = None
        self._reserved_result_queue = None
        self._reserved_pot_workers = []
        self._reserved_task_counter = 0
        self._reservation_active = False
        self.pass_timestep = pass_timestep
        self.pot_kwargs = pot_kwargs
        if self.pass_timestep:
            self.ct = 0
            if self.pot_kwargs is None:
                self.pot_kwargs = {'timestep': 0}
            else:
                self.pot_kwargs['timestep'] = 0
        self._init_pool()

    def _init_pot(self):
        """
        Sets _pot
        """
        # Go to potential directory that houses python function and assign a self._pot variable to it
        self._curdir = os.getcwd()
        os.chdir(self.potential_directory)
        sys.path.insert(0, os.getcwd())
        module = self.python_file.split(".")[0]
        x = importlib.import_module(module)
        self._pot = getattr(x, self.potential_function)
        # leave pool workers there

    def _init_pool(self):
        if self.num_cores <= 0:
            print('Weird number of cores specified. Defaulting to 1...')
            self.num_cores = 1
        if self.pool_num_cores < self.num_cores:
            self.pool_num_cores = self.num_cores
        # TODO: mp.Pool() still uses the platform default start method. On
        # Python 3.12/Linux this may fork from a multithreaded parent and warn
        # or deadlock; Python 3.14 changes the POSIX default to forkserver, but
        # this class is not forkserver/spawn-safe because workers rely on
        # inheriting the parent-imported self._pot. Refactor to use an explicit
        # context, a worker initializer, and a module-level worker call wrapper.
        self._init_pot()
        self._reserved_task_queue = mp.Queue()
        self._reserved_result_queue = mp.Queue()
        self._potPool = mp.Pool(self.pool_num_cores,
                                initializer=_init_reserved_potential_queues,
                                initargs=(self._reserved_task_queue, self._reserved_result_queue))
        os.chdir(self._curdir)

    def _start_reserved_potential_workers(self, num_workers=1):
        if self._reservation_active:
            return
        if self._potPool is None:
            raise RuntimeError("Cannot reserve potential workers before the pool is initialized.")
        if num_workers != 1:
            raise NotImplementedError("Reserved potential workers currently support only num_workers=1.")
        if self.pool_num_cores <= self.num_cores:
            raise ValueError("Reserved potential workers require extra shared-pool capacity.")

        self._reserved_pot_workers = [
            self._potPool.apply_async(_reserved_potential_worker, (self._pot,))
            for _ in range(num_workers)
        ]
        self._reservation_active = True

    def _stop_reserved_potential_workers(self):
        if not self._reservation_active:
            return

        for _ in self._reserved_pot_workers:
            self._reserved_task_queue.put(_RESERVED_POT_STOP)

        worker_errors = []
        for worker in self._reserved_pot_workers:
            try:
                worker.get(timeout=10)
            except BaseException as exc:
                worker_errors.append(exc)

        self._reserved_pot_workers = []
        self._reservation_active = False

        if worker_errors:
            raise RuntimeError("Reserved potential worker did not shut down cleanly.") from worker_errors[0]

    def _close_reserved_queues(self):
        for queue_attr in ("_reserved_task_queue", "_reserved_result_queue"):
            queue = getattr(self, queue_attr)
            if queue is None:
                continue
            try:
                queue.close()
                queue.join_thread()
            finally:
                setattr(self, queue_attr, None)

    def _getpot_reserved(self, cds):
        self._reserved_task_counter += 1
        task_id = self._reserved_task_counter
        if self.pot_kwargs is None:
            pot_kwargs = None
        else:
            try:
                pot_kwargs = self.pot_kwargs.copy()
            except AttributeError:
                pot_kwargs = self.pot_kwargs
        self._reserved_task_queue.put((_RESERVED_POT_CALL, task_id, cds, pot_kwargs))

        while True:
            result_task_id, ok, result, err = self._reserved_result_queue.get()
            if result_task_id != task_id:
                continue
            if ok:
                return result
            raise RuntimeError(f"Reserved potential worker failed:\n{err}")

    def resize_pool(self, num_cores):
        """Ensure the backing pool has at least num_cores workers without changing potential-call chunking."""
        if num_cores <= 0:
            raise ValueError("Potential pool requires num_cores > 0.")
        if num_cores <= self.pool_num_cores:
            return
        self._stop_reserved_potential_workers()
        if self._potPool is not None:
            self._potPool.close()
            self._potPool.join()
            self._potPool = None
        self._close_reserved_queues()
        self.pool_num_cores = num_cores
        self._init_pool()

    @property
    def pool(self):
        """Returns the potential manager's pool so that it can be used internally with Imp Samp or with the user elsewhere"""
        return self._potPool

    def getpot(self, cds, timeit=False):
        """
        Uses the potential function we got to call potential
        :param cds: A stack of geometries (nxmx3, n=num_geoms;m=num_atoms;3=x,y,z) whose energies we need
        :type cds: np.ndarray
        :param timeit: The logger telling the potential manager whether or not to time the potential call
        :type timeit: bool
        """
        if timeit:
            start = time.time()
        if self._reservation_active:
            v = self._getpot_reserved(cds)
        elif self._potPool is not None:
            from itertools import repeat
            cds = np.array_split(cds, self.num_cores)
            if self.pot_kwargs is not None:
                res = self._potPool.starmap(self._pot, zip(cds, repeat(self.pot_kwargs, len(cds))))
            else:
                res = self._potPool.map(self._pot, cds)
            v = np.concatenate(res)
        else:
            v = self._pot(cds)

        if self.pass_timestep:
            self.pot_kwargs['timestep'] += 1

        if timeit:
            elapsed = time.time() - start
            return v, elapsed
        else:
            return v

    def mp_close(self):
        reserved_shutdown_error = None
        try:
            self._stop_reserved_potential_workers()
        except BaseException as exc:
            reserved_shutdown_error = exc

        if self._potPool is not None:
            if reserved_shutdown_error is None:
                self._potPool.close()
                self._potPool.join()
            else:
                self._potPool.terminate()
                self._potPool.join()
            self._potPool = None

        self._close_reserved_queues()

        if reserved_shutdown_error is not None:
            raise reserved_shutdown_error


class Potential_NoMP:
    """
    Version of Potential where no multiprocessing is included. As such, it does not leave a worker in the potential
    directory of interest. If you need to cd into the directory to call a potential (for example, the potential
    loads in a file using a relative path or something), then use ch_dir=True. Not the default since it is
    computationally inefficient to cd during each potential call when not necessary.
    """

    def __init__(self,
                 potential_function,
                 potential_directory,
                 python_file,
                 pass_timestep=False,
                 ch_dir=False,
                 pot_kwargs=None):
        self.potential_function = potential_function
        self.python_file = python_file
        self.pass_timestep = pass_timestep
        self.potential_directory = potential_directory
        self.pot_kwargs = pot_kwargs
        if self.pass_timestep:
            if self.pot_kwargs is None:
                self.pot_kwargs = {'timestep': 0}
            else:
                self.pot_kwargs['timestep'] = 0
        self.ch_dir = ch_dir
        self._init_pot()

    def _init_pot(self):
        self._curdir = os.getcwd()
        os.chdir(self.potential_directory)
        sys.path.insert(0, os.getcwd())
        module = self.python_file.split(".")[0]
        x = importlib.import_module(module)
        self._pot = getattr(x, self.potential_function)
        os.chdir(self._curdir)

    def getpot(self, cds, timeit=False):
        """
        Uses the potential function we got to call potential
        :param cds: A stack of geometries (nxmx3, n=num_geoms;m=num_atoms;3=x,y,z) whose energies we need
        :type cds: np.ndarray
        :param timeit: The logger telling the potential manager whether or not to time the potential call
        :type timeit: bool
        """
        if timeit:
            start = time.time()

        if not self.ch_dir:
            if self.pot_kwargs is not None:
                v = self._pot(cds, self.pot_kwargs)
            else:
                v = self._pot(cds)
        else:
            # Change to the potential directory and then change back after call
            os.chdir(self.potential_directory)
            if self.pot_kwargs is not None:
                v = self._pot(cds, self.pot_kwargs)
            else:
                v = self._pot(cds)
            os.chdir(self._curdir)
        if self.pass_timestep:
            self.pot_kwargs['timestep'] += 1
        if timeit:
            elapsed = time.time() - start
            return v, elapsed
        else:
            return v


class NN_Potential(Potential_NoMP):
    """
    Subclass of Potential_NoMP, where a model argument is provided for convenience
    """

    def __init__(self,
                 potential_function,
                 potential_directory,
                 python_file,
                 model,
                 ch_dir=False,
                 pot_kwargs=None,
                 pass_timestep=False):
        super().__init__(potential_function, potential_directory, python_file, pass_timestep, ch_dir, pot_kwargs)
        self.model = model
        # Kwargs: if passed to NN_Potential, override Potential_NoMP default values vv
        self.ch_dir = ch_dir
        self.pot_kwargs = pot_kwargs

    def getpot(self, cds, timeit=False):
        """
        Subclass of Potential_NoMP, but with an explicit argument passed for the NN model for convenience.
        """
        if timeit:
            start = time.time()
        if self.pot_kwargs is not None:
            v = self._pot(cds, self.model, self.pot_kwargs)
        else:
            v = self._pot(cds, self.model)

        if self.pass_timestep:
            self.pot_kwargs['timestep'] += 1

        if timeit:
            elapsed = time.time() - start
            return v, elapsed
        else:
            return v


class Potential_Direct:
    """
    Version of Potential where the actual Python function is passed rather than
    being imported from an external file. At the request of Mark.
    """

    def __init__(self,
                 potential_function,
                 pot_kwargs=None,
                 pass_timestep=False):
        self.potential_function = potential_function
        self.pot_kwargs = pot_kwargs
        self.pass_timestep = pass_timestep
        if self.pass_timestep:
            self.ct = 0
            if self.pot_kwargs is None:
                self.pot_kwargs = {'timestep': 0}
            else:
                self.pot_kwargs['timestep'] = 0

    def getpot(self, cds, timeit=False):
        if timeit:
            start = time.time()

        if self.pot_kwargs is not None:
            v = self.potential_function(cds, self.pot_kwargs)
        else:
            v = self.potential_function(cds)

        if self.pass_timestep:
            self.pot_kwargs['timestep'] += 1

        if timeit:
            elapsed = time.time() - start
            return v, elapsed
        else:
            return v
